name: Deploiement le site MARP vers GitHub Pages
concurrency: marp-to-pages

on:
  push:
    branches: [ main ]
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Ensure build dir exists
        run: mkdir -p build

      - name: Copy images directory (if exists)
        run: if [[ -d presentation/images ]]; then cp -R presentation/images /build/images; fi

      - name: Build HTML from Build (slide.md)
        uses: docker://marpteam/marp-cli:v3.4.0
        with:
          args: presentation/slide.md -o build/index.html --html
          volume: ${{ github.workspace }}/presentation:/home/marp/app
        env:
          MARP_USER: root:root

      - name: Build PDF from Marp  (slide.pdf)
        uses: docker://marpteam/marp-cli:v3.4.0
        with:
          args: slide.md --allow-local-files -o build/slide.pdf --pdf
          volume: ${{ github.workspace }}/presentation:/home/marp/app          
        env:
          MARP_USER: root:root

      - name: Build PPTX from Marp (slide.pptx)
        uses: docker://marpteam/marp-cli:v3.4.0
        with:
          args: slide.md --allow-local-files -o build/slide.pptx --pptx
          volume: ${{ github.workspace }}/presentation:/home/marp/app          
        env:
          MARP_USER: root:root

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: 'build'

      - name: Deploy production to GitHub Pages
        if: ${{ github.event_name == 'push' }}
        id: deployment
        uses: actions/deploy-pages@v4
          
